# Gitlab ci/cd file configuration

variables:
    REF: "master"
    TOOLCHAIN_PATH: "/matieres/3MMCEP/riscv/bin"
    TOCLEAN: "bin program config .git .gitlab-ci.yml"

stages:
    - test
    - eval
    - cleanup

student_test:
    stage: test
    only:
        - master
    before_script:
        # Check the version of the tools we use
        - awk --version | head -n 1
        - cpp --version | head -n 1
        - git --version
        #- make --version | head -n 1
        - sed --version | head -n 1
    script:
        - for tp in tp1 tp2 tp3 tp4 tp5; do (cd $tp; make -s clean; ../common/verif_etud.sh); done
    artifacts:
        paths:
            - tp*/test/*.sortie  # Pour savoir quoi évaluer mais contenu ignoré
            - tp*/*.s

trigger_eval:
    stage: eval
    only:
        - master
    dependencies:
        - student_test
    before_script:
        # Check the version of the tools we use
        - curl --version | head -n 1
    script:
        - rm -rvf ${TOCLEAN}
        - curl $OPT --request POST --form "token=${EVAL_TOKEN}" --form ref=${REF} ${REP}/api/v4/projects/${EVAL_PROJECT_ID}/trigger/pipeline

cleanup_job:
    stage: cleanup
    script:
        - echo "On failure job -> cleaning sensitive data"
        - rm -rvf ${TOCLEAN}
    when: on_failure
